In [5]:
import numpy as np
from matplotlib import pyplot as plt


import numpy as np
np_arr1 = np.array([1,2,3,4])
np_arr2 = np.array([5,6,7,8])
print(  np.column_stack ((np_arr1, np_arr2))     )

print(  np.row_stack ((np_arr1, np_arr2)))

# np.column_stack

# np.row_stack





[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 2 3 4]
 [5 6 7 8]]
